<a href="https://colab.research.google.com/github/Amalusebastian/ICT-DSA-Assignments/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A company stores salaries in a NumPy array.

salaries = np.array([45000, 52000, 61000, 48000, 75000])

Tasks:

1.
Increase all salaries by 10%.

2.
Find the average salary.

3.
Find the maximum and minimum salary.

4.
Print salaries greater than 60000.

In [6]:
#importing libraries
import numpy as np
import pandas as pd
salaries = np.array([45000, 52000, 61000, 48000, 75000])


In [5]:
# increase slaries by 10%
salaries_new= salaries * 1.10
print(salaries_new)

[49500. 57200. 67100. 52800. 82500.]


In [9]:
#average salary
average=np.average(salaries)
print(average)


56200.0


In [10]:
# max and min salary
max_salary=np.max(salaries)
min_salary=np.min(salaries)

print(max_salary)
print(min_salary)

75000
45000


In [11]:
# salaries greater than 60000
for i in salaries:
  if (i >60000):
    print(i)

61000
75000


Q2. Sales Data Analysis

Daily sales of a store for 10 days:
sales = np.array([120,150,180,200,170,160,210,220,190,175])

Tasks:
1.
Compute total sales.

2.
Compute mean and standard deviation.

3.
Identify days where sales exceeded the average.

4.
Normalize the sales using Min-Max scaling.

In [7]:
#importing libraries
import numpy as np
import pandas as pd
sales = np.array([120,150,180,200,170,160,210,220,190,175])

In [8]:
# total sales.
total_sales=np.sum(sales)
print(total_sales)

1775


In [9]:
#mean and standard deviation
sales_mean=np.mean(sales)
sales_deviation=np.std(sales)
print(sales_mean)
print(sales_deviation)

177.5
28.217902119044926


In [15]:
# days where sales exceeded the average
average_sales=np.average(sales)
print(average_sales)
for i in sales:
  if (i > average_sales):
    print(i)

177.5
180
200
210
220
190


In [13]:
# min max scaling
min_val=np.min(sales)
max_val=np.max(sales)
scaled_data=(sales-min_val)/(max_val-min_val)
print(scaled_data)

[0.   0.3  0.6  0.8  0.5  0.4  0.9  1.   0.7  0.55]


Q3. Matrix Operations for Business Data

A company has sales data for 3 products across 4 regions.

sales_matrix = np.array([
[120,140,130,150],
[80,90,100,95],
[200,210,190,205]
])
Tasks:

1.
Find total sales per product.

2.
Find total sales per region.

3.
Identify the best performing product.

4.
Identify the region with highest sales.

In [32]:
# row-product
#column-region
import numpy as np
import pandas as pd
sales_matrix = np.array([ [120,140,130,150], [80,90,100,95], [200,210,190,205] ])
sales_matrix

array([[120, 140, 130, 150],
       [ 80,  90, 100,  95],
       [200, 210, 190, 205]])

In [35]:
#total sales per product
total_sales_product=np.sum(sales_matrix, axis=1)
print(total_sales_product)

[540 365 805]


In [36]:
#total sales per region
total_sales_region=np.sum(sales_matrix, axis=0)
print(total_sales_region)

[400 440 420 450]


In [29]:
# best product
best_product=np.argmax(total_sales_product)
print(best_product)
best_product1=np.max(total_sales_product)
print(best_product1)

# product 3 is best performing product as it total is 805





2
805


In [30]:
#best_sales - region 4
highest_sales_region=np.argmax(total_sales_region)
print(highest_sales_region)

3


Q4. Employee Dataset Exploration

Create a DataFrame:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4]
}
Tasks:

1.
Convert this dictionary into a DataFrame.

2.
Display basic statistics of the dataset.

3.
Find the average salary per department.

4.
Identify employees with experience greater than 4 years.

5.
Add a new column Bonus = 10% of salary.


In [3]:
import numpy as np
import pandas as pd
data = {
     'Employee':['A','B','C','D','E','F'],
     'Department':['HR','IT','IT','Finance','HR','Finance'],
     'Salary':[50000,65000,70000,72000,52000,68000],
     'Experience':[2,5,7,6,3,4] }
print(data)



{'Employee': ['A', 'B', 'C', 'D', 'E', 'F'], 'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'Finance'], 'Salary': [50000, 65000, 70000, 72000, 52000, 68000], 'Experience': [2, 5, 7, 6, 3, 4]}


In [6]:
# dictionary into dataframe
employee_df=pd.DataFrame(data)
employee_df

,Employee,Department,Salary,Experience
0,A,HR,50000,2
1,B,IT,65000,5
2,C,IT,70000,7
3,D,Finance,72000,6
4,E,HR,52000,3
5,F,Finance,68000,4


In [7]:
# basic statistics of the dataset.
employee_df.describe()

,Salary,Experience
count,6.000000,6.000000
mean,62833.333333,4.500000
std,9474.527253,1.870829
min,50000.000000,2.000000
25%,55250.000000,3.250000
50%,66500.000000,4.500000
75%,69500.000000,5.750000
max,72000.000000,7.000000


In [8]:
#average salary per department
employee_df.groupby('Department')['Salary'].mean()

,Salary
Department,
Finance,70000.0
HR,51000.0
IT,67500.0


In [14]:
# employess greater that 4 year of experience
employee_df[employee_df['Experience']>4].sort_values(by='Employee', ascending=False)
#Employess 'D', 'C' and 'B'

,Employee,Department,Salary,Experience,Bonus
3,D,Finance,72000,6,7200.0
2,C,IT,70000,7,7000.0
1,B,IT,65000,5,6500.0


In [10]:
# new column "Bonus"= 10% of salary
employee_df['Bonus']=employee_df['Salary']*0.10
employee_df

,Employee,Department,Salary,Experience,Bonus
0,A,HR,50000,2,5000.0
1,B,IT,65000,5,6500.0
2,C,IT,70000,7,7000.0
3,D,Finance,72000,6,7200.0
4,E,HR,52000,3,5200.0
5,F,Finance,68000,4,6800.0


Q5. Missing Data Handling

Dataset:

data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}

Tasks:

1.
Detect missing values.

2.
Replace missing Age with mean age.

3.
Replace missing Salary with median salary

4. Remove rows with any remaining missing valuesEmployee

In [16]:
import pandas as pd
data = { 'Name':['John','Anna','Peter','Linda','David'], 'Age':[28, np.nan, 35, 32, np.nan], 'Salary':[50000,54000,np.nan,58000,60000] }
emp_df=pd.DataFrame(data)
print(emp_df)

    Name   Age   Salary
0   John  28.0  50000.0
1   Anna   NaN  54000.0
2  Peter  35.0      NaN
3  Linda  32.0  58000.0
4  David   NaN  60000.0


In [18]:
# detect missing values
emp_df.isnull()

,Name,Age,Salary
0,False,False,False
1,False,True,False
2,False,False,True
3,False,False,False
4,False,True,False


In [20]:
emp_df.isna().sum()

,0
Name,0
Age,2
Salary,1


In [24]:
# replace missing age  with mean age
emp_df['Age'].fillna(emp_df['Age'].mean(),inplace=True)
emp_df

/tmp/ipykernel_350/3653900865.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_df['Age'].fillna(emp_df['Age'].mean(),inplace=True)


,Name,Age,Salary
0,John,28.000000,50000.0
1,Anna,31.666667,54000.0
2,Peter,35.000000,NaN
3,Linda,32.000000,58000.0
4,David,31.666667,60000.0


In [25]:
# replace missing Salary with median salary
emp_df['Salary'].fillna(emp_df['Age'].median(),inplace=True)
emp_df

/tmp/ipykernel_350/2760948641.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_df['Salary'].fillna(emp_df['Age'].median(),inplace=True)


,Name,Age,Salary
0,John,28.000000,50000.000000
1,Anna,31.666667,54000.000000
2,Peter,35.000000,31.666667
3,Linda,32.000000,58000.000000
4,David,31.666667,60000.000000


In [30]:
#Remove rows with any remaining missing values
emp_df_new=emp_df.dropna(axis=0)
emp_df_new

,Name,Age,Salary
0,John,28.000000,50000.000000
1,Anna,31.666667,54000.000000
2,Peter,35.000000,31.666667
3,Linda,32.000000,58000.000000
4,David,31.666667,60000.000000


Q6. Sales Performance Analysis

Dataset:

sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}
Tasks:

1.
Find total sales per region.

2.
Identify the top salesperson.

3.
Compute average sales across regions.

4.
Sort the dataset by sales descending.

In [38]:
import numpy as np
import pandas as pd
sales_data = { 'Region':['North','South','East','West','North','South','East','West'], 'Salesperson':['A','B','C','D','E','F','G','H'], 'Sales':[12000,15000,13000,17000,16000,14000,15500,16500] }

In [41]:
#total sales per region
sales_data=pd.DataFrame(sales_data)
sales_data

,Region,Salesperson,Sales
0,North,A,12000
1,South,B,15000
2,East,C,13000
3,West,D,17000
4,North,E,16000
5,South,F,14000
6,East,G,15500
7,West,H,16500


In [44]:
sales_data.groupby('Region')['Sales'].sum()

,Sales
Region,
East,28500
North,28000
South,29000
West,33500


In [46]:
# top salesperson.
sales_data.sort_values(by='Sales', ascending=False)
# Salesperson D has highest sales=17000

,Region,Salesperson,Sales
3,West,D,17000
7,West,H,16500
4,North,E,16000
6,East,G,15500
1,South,B,15000
5,South,F,14000
2,East,C,13000
0,North,A,12000


In [47]:
# average sales across regions
sales_data.groupby('Region')['Sales'].mean()

,Sales
Region,
East,14250.0
North,14000.0
South,14500.0
West,16750.0


In [48]:
#Sort the dataset by sales descending
sales_data.sort_values(by='Sales', ascending=False)

,Region,Salesperson,Sales
3,West,D,17000
7,West,H,16500
4,North,E,16000
6,East,G,15500
1,South,B,15000
5,South,F,14000
2,East,C,13000
0,North,A,12000


Q7. Customer Purchase Analysis

Dataset:

data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}
Tasks:

1.
Find the average purchase amount by city.

2.
Identify customers with purchase above overall average.

3.
Find the city generating the highest revenue.


4.
Create a column Age_Group:
o
<30 → Young
o
30–50 → Adult
o
50 → Senior

5.
Find average purchase per age group.

In [50]:
import pandas as pd
data = { 'CustomerID':[101,102,103,104,105,106,107], 'Age':[25,45,35,50,23,40,60], 'PurchaseAmount':[250,600,400,800,150,700,900], 'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai'] }
cust_df=pd.DataFrame(data)
cust_df

,CustomerID,Age,PurchaseAmount,City
0,101,25,250,Delhi
1,102,45,600,Mumbai
2,103,35,400,Delhi
3,104,50,800,Chennai
4,105,23,150,Mumbai
5,106,40,700,Delhi
6,107,60,900,Chennai


In [51]:
#average purchase amount by city
cust_df.groupby('City')['PurchaseAmount'].mean()

,PurchaseAmount
City,
Chennai,850.0
Delhi,450.0
Mumbai,375.0


In [54]:
#customers with purchase above overall average
avg_purchase =cust_df['PurchaseAmount'].mean()
avg_purchase


np.float64(542.8571428571429)

In [56]:
cust_df[cust_df['PurchaseAmount']>avg_purchase]

,CustomerID,Age,PurchaseAmount,City
1,102,45,600,Mumbai
3,104,50,800,Chennai
5,106,40,700,Delhi
6,107,60,900,Chennai


In [ ]:
# customers 102,104,107 and 106

In [57]:
#city generating the highest revenue
cust_df.groupby('City')['PurchaseAmount'].sum()

# Ans: Chennai  is the city

,PurchaseAmount
City,
Chennai,1700
Delhi,1350
Mumbai,750


In [58]:
#new column age_group
cust_df

,CustomerID,Age,PurchaseAmount,City
0,101,25,250,Delhi
1,102,45,600,Mumbai
2,103,35,400,Delhi
3,104,50,800,Chennai
4,105,23,150,Mumbai
5,106,40,700,Delhi
6,107,60,900,Chennai


In [60]:
def categorize_age(age):
    if age < 30:
        return 'Young'
    elif 30 <= age < 50:
        return 'Adult'
    else:  # age >= 50
        return 'Senior'

# Create the Age_Group column
cust_df['Age_Group'] = cust_df['Age'].apply(categorize_age)
cust_df

,CustomerID,Age,PurchaseAmount,City,Age_Group
0,101,25,250,Delhi,Young
1,102,45,600,Mumbai,Adult
2,103,35,400,Delhi,Adult
3,104,50,800,Chennai,Senior
4,105,23,150,Mumbai,Young
5,106,40,700,Delhi,Adult
6,107,60,900,Chennai,Senior


In [61]:
# average purchase per age group
cust_df.groupby('Age_Group')['PurchaseAmount'].mean()

,PurchaseAmount
Age_Group,
Adult,566.666667
Senior,850.000000
Young,200.000000


Q8. Time Series Sales Analysis

Generate data:

dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})

Tasks:

1.
Convert Date to datetime index.

2.
Compute monthly percentage growth.

3.
Calculate 3-month rolling average sales.

4.
Identify the month with highest growth rate.

In [62]:
import pandas as pd
import numpy as np

In [84]:
dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})
print(df)


         Date  Sales
0  2024-01-31    200
1  2024-02-29    220
2  2024-03-31    250
3  2024-04-30    270
4  2024-05-31    300
5  2024-06-30    320
6  2024-07-31    350
7  2024-08-31    360
8  2024-09-30    380
9  2024-10-31    400
10 2024-11-30    420
11 2024-12-31    450


/tmp/ipykernel_350/3264387905.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range('2024-01-01', periods=12, freq='M')


In [80]:
df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    12 non-null     datetime64[ns]
 1   Sales   12 non-null     int64         
dtypes: datetime64[ns](1), int64(1)
memory usage: 324.0 bytes


,0
Date,datetime64[ns]
Sales,int64


In [85]:
# Convert Date to datetime index
df['Date'] = pd.to_datetime(df['Date'])

df.set_index('Date', inplace=True)
print(df)


            Sales
Date             
2024-01-31    200
2024-02-29    220
2024-03-31    250
2024-04-30    270
2024-05-31    300
2024-06-30    320
2024-07-31    350
2024-08-31    360
2024-09-30    380
2024-10-31    400
2024-11-30    420
2024-12-31    450
Sales    int64
dtype: object


In [86]:
print(df.dtypes)

Sales    int64
dtype: object


In [88]:
#monthly percentage growth
df['Monthly_Growth_%']= df['Sales'].pct_change() * 100
df

,Sales,Monthly_Growth_%
Date,,
2024-01-31,200,NaN
2024-02-29,220,10.000000
2024-03-31,250,13.636364
2024-04-30,270,8.000000
2024-05-31,300,11.111111
2024-06-30,320,6.666667
2024-07-31,350,9.375000
2024-08-31,360,2.857143
2024-09-30,380,5.555556


In [89]:
#3-month rolling average sales.
df['3M_Rolling_Avg'] = df['Sales'].rolling(window=3).mean()
print(df)

            Sales  Monthly_Growth_%  3M_Rolling_Avg
Date                                               
2024-01-31    200               NaN             NaN
2024-02-29    220         10.000000             NaN
2024-03-31    250         13.636364      223.333333
2024-04-30    270          8.000000      246.666667
2024-05-31    300         11.111111      273.333333
2024-06-30    320          6.666667      296.666667
2024-07-31    350          9.375000      323.333333
2024-08-31    360          2.857143      343.333333
2024-09-30    380          5.555556      363.333333
2024-10-31    400          5.263158      380.000000
2024-11-30    420          5.000000      400.000000
2024-12-31    450          7.142857      423.333333


In [91]:
# month with highest growth rate
max_growth_rate= df['Monthly_Growth_%'].max()
max_growth_rate

# Its march with 13.63

13.636363636363647